### ISSUE TITLE
Создать список используемых видеокамер

### ISSUE THREAD

**Issue by NikitaZhidov** [ParkingEyeTeam/ParkingEye#5]

**Comment by Fragers** [comment]
https://moidom.citylink.pro/pub/10491
https://moidom.citylink.pro/pub/10493
https://moidom.citylink.pro/pub/10495

**Comment by Fragers** [comment]
Hls потоки заканчиваются на .m3u8.

![изображение](https://user-images.githubusercontent.com/48284978/156513576-9bcb53a3-8682-495d-9e24-63250fb6eed5.png) - часть, связанная с потоком у сампо.

Можно смотреть через vlc/ffmpeg.

**Comment by Fragers** [comment]
У ситилинка

![изображение](https://user-images.githubusercontent.com/48284978/156514131-56f4fc65-d854-4d5b-8fa6-33ce4985fd46.png)
